---

# The project Docker compose file for development.

version: '2'

services:
  config:
    extends:
      file: docker-compose-lib.yaml
      service: config

  ## print:
  ##   extends:
  ##     file: docker-compose-lib.yaml
  ##     service: print
  ##   volumes_from:
  ##     - config:ro

  qgisserver:
    extends:
      file: docker-compose-lib.yaml
      service: qgisserver
    volumes_from:
      - config:ro
      # Single QGIS project files
    environment:
      - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgz
      - GEOMAPFISH_OGCSERVER=qgis
  
  redis:
    extends:
      file: docker-compose-lib.yaml
      service: redis

  geoportal:
    extends:
      file: docker-compose-lib.yaml
      service: geoportal
    volumes_from:
      - config:ro
    volumes:
      - /var/sig:/var/sig:ro
    environment:
      - C2CWSGIUTILS_CONFIG=/app/production.ini

  alembic:
    extends:
      file: docker-compose-lib.yaml
      service: alembic

  front:
    extends:
      file: docker-compose-lib.yaml
      service: front
    volumes_from:
      - config:ro

  tilecloudchain:
    extends:
      file: docker-compose-lib.yaml
      service: tilecloudchain
    volumes_from:
      - config:ro

  tilegeneration_slave:
    extends:
      file: docker-compose-lib.yaml
      service: tilegeneration_slave
    volumes_from:
      - config:ro

  # Rich image for project development with e.-g. vim, tree, awscli, psql, ...
  tools:
    volumes_from:
      - config:rw
    extends:
      file: docker-compose-lib.yaml
      service: tools
